spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:usuario}:${MONGO_PASSWORD:password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:productsdb}?authSource=admin

server:
  port: ${SERVER_PORT:8080}  # ← En producción usás variable de entorno o puerto fijo

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka/}
    enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${HOSTNAME:${random.uuid}}  # ← En K8s usa HOSTNAME

logging:
  level:
    root: WARN
    com.microservicescourse: INFO