spring:
  data:
    mongodb:
      uri: mongodb://usuario:password@localhost:27017/productsdb?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    root: INFO
    com.microservicescourse: DEBUG